#!/bin/bash

apt-get install -yq --no-install-recommends \
	pkg-config \
	nasm \
	yasm \
	libgnutls28-dev \
	libv4l-0 \
	libraw1394-11 \
	libavc1394-0 \
	libiec61883-0 \
	libasound2 \
	libopus-dev \
	libgsm1-dev \
	libmodplug-dev \
	libvpx-dev \
	libass-dev \
	libbluray-dev \
	libfribidi-dev \
	libgmp-dev \
	libmp3lame-dev \
	libopencore-amrnb-dev \
	libopencore-amrwb-dev \
	librtmp-dev \
	libtheora-dev \
	libx264-dev \
	libxvidcore-dev \
	libx265-dev \
	libxss1 \
	libgtk2.0-0 \
	libatspi2.0-dev \
	libatk-bridge2.0-dev \
	libopenjp2-7-dev \
	libopenmpt-dev \
	libshine-dev \
	libsnappy-dev \
	libsoxr-dev \
	libspeex-dev \
	libtwolame-dev \
	libvo-amrwbenc-dev \
	libwavpack-dev \
	libsdl2-dev \
	libwebp-dev \
	cmake
  
